clusterRoleBindingName: bridge-operator
clusterRoleBindingNamePSP: bridge-operator-psp
clusterRoleName: bridge-operator
clusterRoleNamePSP: bridge-operator-psp
pspName: bridge-operator-psp

name: bridge-operator
userID: 1000
groupID: 1000
