version: 2.1

orbs:
  architect: giantswarm/architect@4.10.1

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build-bridge-operator
          binary: bridge-operator
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-bridge-operator-to-quay
          image: "quay.io/giantswarm/bridge-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build-bridge-operator
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-bridge-operator-to-aliyun
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/bridge-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build-bridge-operator
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          name: push-bridge-operator-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "bridge-operator"
          requires:
            - push-bridge-operator-to-quay
            - push-bridge-operator-to-aliyun
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-bridge-operator-to-kvm-app-collection
          app_name: "bridge-operator"
          app_collection_repo: "kvm-app-collection"
          requires:
            - push-bridge-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
