apiVersion: v1
kind: ConfigMap
metadata:
  name: bridge-operator-configmap
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:18000'
    service:
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
