apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        releasetime: {{ $.Release.Time }}
    spec:
      volumes:
      - name: bridge-operator-configmap
        configMap:
          name: bridge-operator-configmap
          items:
            - key: config.yaml
              path: config.yaml
      - name: certs
        hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
      - name: flannel-env-files
        hostPath:
          path: /run/flannel/networks/
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs/
      serviceAccountName: bridge-operator
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
      containers:
      - name: bridge-operator
        image: quay.io/giantswarm/bridge-operator:[[ .SHA ]]
        volumeMounts:
        - name: bridge-operator-configmap
          mountPath: /var/run/bridge-operator/configmap/
        - name: certs
          mountPath: /etc/ssl/certs/ca-certificate.crt
        - name: flannel-env-files
          mountPath: /run/flannel/networks/
        - name: ssl-certs
          mountPath: /etc/ssl/certs/
        ports:
        - name: http
          containerPort: 18000
        args:
        - daemon
        - --config.dirs=/var/run/bridge-operator/configmap/
        - --config.files=config
        livenessProbe:
          httpGet:
            path: /healthz
            port: 18000
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 18000
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 250m
            memory: 250Mi
      hostNetwork: true
      imagePullSecrets:
      - name: bridge-operator-pull-secret
