apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: bridge-operator-pull-secret
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ .Values.registry.pullSecret.dockerConfigJSON | quote }}
